"""
Produce a title info listing based on the files in the current
directory.
"""

import os
import re
import time

def maketitfile(directory='.', fname='titleinfo.txt',
                headers=('filename', 'title', 'row2'),
                title='Title',
                row2fmt='data file: {}, file date: {}',
                delim=';', fext=('txt', 'csv')):

    """Produce a listing of the data files in ``directory``.

    Only files with one of the extensions in fext are listed.

    Files with base names, excluding the file extension, not ending with
    a number will be ignored."""

    numrx = r'[-\w]+?(\d+)'
    files = [os.path.basename(fn) for fn in os.listdir(directory) if
             (fn.split('.')[-1] in fext and re.match(numrx, fn.split('.')[0]))]

    header = (delim + ' ').join(h for h in headers) + '\n'
    mess = '# Generated by function maketitfile in module {}\n# {}\n\n'
    mess = mess.format(__name__, time.ctime(time.time()))

    with open(fname, 'w') as fo:
        fo.write(mess)
        fo.write(header)
        delspc = delim + ' '
        for fn in sorted(files):
            fo.write(fn + delspc + title + delspc + row2fmt + '\n')
